// Data.js
import Foto1 from '../../../assets/Models/james-feaver-KMNEkM-VdjE-unsplash.png';
import Foto2 from '../../../assets/Models/ahmad-ebadi-ot28ybNQ-Is-unsplash.png';
import Foto3 from '../../../assets/Models/malik-skydsgaard-d_Y1WiusJnk-unsplash.png';
import Foto4 from '../../../assets/Models/daniil-onischenko-GHf1Dw6oCEc-unsplash.png';
import numberLogo from '../../../assets/Models/2205194_eye_look_monitor_observe_vision_icon.png';


export const cardData = [
  {
    id: 1,
    image: Foto1,
    titleKey: 'cardTitles.card1Title',
    name: 'ANILA CANOLLI',
    priceKey: 'cardPrices.card1Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 2,
    image: Foto2,
    titleKey: 'cardTitles.card2Title',
    name: 'KLEA GASHI',
    priceKey: 'cardPrices.card2Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 3,
    image: Foto3,
    titleKey: 'cardTitles.card3Title',
    name: 'ARI BERISHA',
    priceKey: 'cardPrices.card3Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 4,
    image: Foto4,
    titleKey: 'cardTitles.card4Title',
    name: 'JON KLAIQI',
    priceKey: 'cardPrices.card4Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 5,
    image: Foto1,
    titleKey: 'cardTitles.card1Title',
    name: 'ANILA CANOLLI',
    priceKey: 'cardPrices.card1Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 6,
    image: Foto2,
    titleKey: 'cardTitles.card2Title',
    name: 'KLEA GASHI',
    priceKey: 'cardPrices.card2Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 7,
    image: Foto3,
    titleKey: 'cardTitles.card3Title',
    name: 'ARI BERISHA',
    priceKey: 'cardPrices.card3Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 8,
    image: Foto4,
    titleKey: 'cardTitles.card4Title',
    name: 'JON KLAIQI',
    priceKey: 'cardPrices.card4Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 9,
    image: Foto1,
    titleKey: 'cardTitles.card1Title',
    name: 'ANILA CANOLLI',
    priceKey: 'cardPrices.card1Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 10,
    image: Foto2,
    titleKey: 'cardTitles.card2Title',
    name: 'KLEA GASHI',
    priceKey: 'cardPrices.card2Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 11,
    image: Foto3,
    titleKey: 'cardTitles.card3Title',
    name: 'ARI BERISHA',
    priceKey: 'cardPrices.card3Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
  {
    id: 12,
    image: Foto4,
    titleKey: 'cardTitles.card4Title',
    name: 'JON KLAIQI',
    priceKey: 'cardPrices.card4Price',
    location: 'Prishtina, Kosova',
    numberLogo: numberLogo,
    number: '290',
  },
];

